### PR TITLE
Navbar && minor fixes

### PR DESCRIPTION
**Pull request by samyakbvs**
Added scroll effect in the navbar 
Fixed alignment

Merge it its tested

### CODE REVIEW

**Comment by kartikeya23** [comment]
#1 

@samyakbvs you figured the issue with .scrollTop?

Was it what I said?

**Review by kartikeya23 — APPROVED** [review]
Good Work!
Add a Screenshot though if you can

**Comment by samyakbvs** [comment]
Yes I did it with .scrollTop()
No point providing a ss bcs it is a scroll effect

**Comment by samyakbvs** [comment]
@kartikeya23

**Comment by samyakbvs** [comment]
@MrCrook2711 Please merge and also add collaborators

**Pull request merged**
